spring.application.name=Barber_App

spring.datasource.url=jdbc:postgresql://localhost:5432/barber_booking
spring.datasource.username=postgres
spring.datasource.password=raffaele89
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA/Hibernate ---
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# --- Liquibase ---
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/db.changelog-master.yaml
logging.level.org.springframework.boot.autoconfigure.liquibase=DEBUG
logging.level.liquibase=DEBUG

# Connection Debug (temporary)
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.jdbc=DEBUG
